name: SODSScanner
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
packages:
  ScannerSpectrumCore:
    path: ../scanner-spectrum-core
targets:
  SODSScanneriOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SODSScannerShared
      - path: Platform/iOS
      - path: SODSScanneriOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strangelab.sods.scanner
        INFOPLIST_FILE: SODSScanneriOS/Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.strangelab.sods.scanner.local
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGN_ENTITLEMENTS: SODSScanneriOS/Resources/SODSScanneriOS.Debug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: SODSScanneriOS/Resources/SODSScanneriOS.entitlements
    dependencies:
      - package: ScannerSpectrumCore
        product: ScannerSpectrumCore
      - package: ScannerSpectrumCore
        product: SODSAppCore
    scheme:
      gatherCoverageData: false
      testTargets:
        - SODSScanneriOSTests

  SODSScannermacOS:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: SODSScannerShared
      - path: Platform/macOS
      - path: SODSScanneriOS
        excludes:
          - Resources/LaunchScreen.storyboard
          - Resources/SODSScanner.storekit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strangelab.sods.scanner.macos
        PRODUCT_NAME: SODS Scanner
        INFOPLIST_FILE: SODSScanneriOS/Resources/Info-macOS.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
      configs:
        Debug:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: ScannerSpectrumCore
        product: ScannerSpectrumCore
      - package: ScannerSpectrumCore
        product: SODSAppCore

  SODSScanneriOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.strangelab.sods.scanner.tests
      configs:
        Debug:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
    sources:
      - path: SODSScanneriOSTests
    dependencies:
      - target: SODSScanneriOS

schemes:
  SODSScannermacOS:
    build:
      targets:
        SODSScannermacOS: all
    run:
      config: Debug
