#!/usr/bin/env bash

AUX_HOST="${AUX_HOST:-192.168.8.114}"
LOGGER_HOST="${LOGGER_HOST:-192.168.8.160}"
MAC2_HOST="${MAC2_HOST:-192.168.8.214}"
AUX_CIDR="${AUX_CIDR:-192.168.8.0/24}"
AUX_GATEWAY="${AUX_GATEWAY:-192.168.8.1}"

LIVEKIT_URL="${LIVEKIT_URL:-ws://${AUX_HOST}:7880}"
TOKEN_ENDPOINT="${TOKEN_ENDPOINT:-http://${AUX_HOST}:9123/token}"
GOD_GATEWAY_URL="${GOD_GATEWAY_URL:-http://${AUX_HOST}:8099/god}"
VAULT_INGEST_URL="${VAULT_INGEST_URL:-http://${LOGGER_HOST}:8088/v1/ingest}"
OPS_FEED_URL="${OPS_FEED_URL:-http://${AUX_HOST}:9101}"

SODS_PORT="${SODS_PORT:-9123}"
SODS_STATION_URL="${SODS_STATION_URL:-http://localhost:${SODS_PORT}}"

PI_LOGGER_URL="${PI_LOGGER_URL:-${SODS_LOGGER_URL:-http://${AUX_HOST}:9101,http://pi-logger.local:8088,http://${LOGGER_HOST}:8088}}"
PI_LOGGER="${PI_LOGGER:-$PI_LOGGER_URL}"

TOKEN_URL="${TOKEN_URL:-$TOKEN_ENDPOINT}"
GOD_URL="${GOD_URL:-$GOD_GATEWAY_URL}"
VAULT_URL="${VAULT_URL:-$VAULT_INGEST_URL}"

AUX_SSH="${AUX_SSH:-pi@${AUX_HOST}}"
LOGGER_SSH="${LOGGER_SSH:-pi@${LOGGER_HOST}}"
MAC2_SSH="${MAC2_SSH:-letsdev@${MAC2_HOST}}"

PI_AUX_ADMIN_SSH="${PI_AUX_ADMIN_SSH:-$AUX_SSH}"
PI_LOGGER_ADMIN_SSH="${PI_LOGGER_ADMIN_SSH:-$LOGGER_SSH}"
MAC2_ADMIN_SSH="${MAC2_ADMIN_SSH:-$MAC2_SSH}"

REMOTE_HOST="${REMOTE_HOST:-$MAC2_SSH}"
